workflow: Add notify step

diff --git a/.github/workflows/dev-cicd-aws.yaml b/.github/workflows/dev-cicd-aws.yaml
--- a/.github/workflows/dev-cicd-aws.yaml
+++ b/.github/workflows/dev-cicd-aws.yaml
@@ -30,11 +30,14 @@ jobs:
       steps:
       - name: Source Code Checkout
         uses: actions/checkout@v4 
-
       - name: Set up JDK 17
         uses: actions/setup-java@v4
         with:
           java-version: '17'
-          distribution: 'temurin'
       - name: Run test java
         run: ./gradlew test
+      - name: Notify on Failure
+        if: failure()
+        run: |
+          echo "Tests failed! Pipeline will be stopped."
+          exit 1
